# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in rinzler-vulkan.gemspec
gemspec

gem "numo-narray", path: "/home/matrix9180/Projects/numo-narray"

gem "irb"
gem "rake", "~> 13.0"
gem "rake-compiler"
