# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in rinzler-nn.gemspec
gemspec

gem "rinzler-tensor", path: "../rinzler-tensor"
gem "numo-narray",    path: "/home/matrix9180/Projects/numo-narray"

gem "irb"
gem "rake", "~> 13.0"
